// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unwpfgclmsqnueyfueio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVud3BmZ2NsbXNxbnVleWZ1ZWlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NjQzNDIsImV4cCI6MjA1ODI0MDM0Mn0.JUTUU9K9cDvR9Eh8b1Yp3tFKWC8wdWalZ_1Sw6936I8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);